<?php

namespace fixsickcoder\ServiceAuthentication\Controller;

use fixsickcoder\JsonRpc\Controller;
use fixsickcoder\JsonRpc\Exception;
use fixsickcoder\ServiceAuthentication\DTO\UserDTO;
use fixsickcoder\ServiceAuthentication\DTO\UserId;
use fixsickcoder\ServiceAuthentication\DTO\UserLoginDTO;
use fixsickcoder\ServiceAuthentication\Interface\UserInterface;
use fixsickcoder\ServiceAuthentication\Service\UserService;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class UserController extends Controller
{

    /**
     * Конструктор
     *
     * @param UserService $service
     */
    public function __construct(
        private readonly UserInterface $service
    )
    {
    }

    /**
     * End-point для контроллера
     *
     * @param Request $request
     * @return JsonResponse
     */
    #[Route('/users')]
    public function index(Request $request): JsonResponse
    {
        return parent::index($request); // TODO: Change the autogenerated stub
    }

    /**
     * Аутентифкация пользователя
     *
     * @param UserLoginDTO $params Параметры для аутентификации пользователя
     * @return array
     */
    public function login(UserLoginDTO $params): array
    {
        return $this->service->login($params->toArray());
    }

    /**
     * Получение данных пользователя для пользователя
     *
     * @param string $id
     * @return array
     */
    public function info(string $id): array
    {
        return $this->service->info($id);
    }


    /**
     * Добовление пользователя
     *
     * @param UserDTO $params
     * @return array
     * @throws Exception
     */
    public function add(UserDTO $params): array
    {
//        return [1];
        return  $this->service->add($params->toArray());
    }

    /**
     * Удаление пользователя
     *
     * @param string $id Идентфиикатор записи пользователя
     *
     * @return array
     */
    public function remove(string $id): array
    {
        return $this->service->remove($id);
    }

    /**
     * Обновление данных пользователя
     *
     * @param UserId $params
     * @return array
     */
    public function update(UserId $params): array
    {
        return  $this->service->edit([]);
    }

    /**
     * Получение данных пользователя для администратора
     *
     * @param string $id Идентификатор записи пользователя
     *
     * @return array
     */
    public function get(string $id): array
    {
        return $this->service->get($id);
    }
}